Tasks

diff --git a/0x1C-makefiles/100-Makefile b/0x1C-makefiles/100-Makefile
--- a/0x1C-makefiles/100-Makefile
+++ b/0x1C-makefiles/100-Makefile
@@ -7,6 +7,10 @@ CFLAGS= -Wall -Werror -Wextra -pedantic
 .PHONY: all clean oclean fclean re
 all:$(NAME)
 $(NAME): $(wildcard *.o) $(HEADER)
+	@if [ ! -e "$(HEADER)" ]; then
+		echo "$(HEADER) is missing.";
+		exit 1;
+	fi
 	$(CC) -Wall -Werror -Wextra -pedantic $(wildcard *.o) -o $(NAME)
 clean:
 	$(RM) *~ $(NAME)
